apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: bookinfo-network-delay
  namespace: default
spec: 
  # It can be delete/retain
  jobCleanUpPolicy: 'retain'
  # It can be true/false
  annotationCheck: 'false'
  # It can be active/stop
  engineState: 'active'
  monitoring: false
  appinfo: 
    appns: 'default'
    # FYI, To see app label, apply kubectl get pods --show-labels
    applabel: 'app=ratings'
    appkind: 'deployment'
  chaosServiceAccount: pod-network-latency-sa
  experiments:
    - name: pod-network-latency
      spec:
        components:
          env:
            #Network interface inside target container
            - name: NETWORK_INTERFACE
              value: 'eth0'     

            - name: NETWORK_LATENCY
              value: '2000'

            - name: TOTAL_CHAOS_DURATION
              value: '100' # in seconds

            - name: PODS_AFFECTED_PERC
              value: '100'  
        probe:
          - name: "check-product-details"
            type: "httpProbe"
            httpProbe/inputs:
              url: "http://productpage/productpage"
              insecureSkipVerify: true
              method:
                get: 
                  criteria: == # supports == & != and oneof operations
                  responseCode: "200"
            mode: "Continuous"
            runProperties:
              probeTimeout: 5
              interval: 5
              retry: 1
              probePollingInterval: 2